app/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from app import db, login
import bleach
from markdown import markdown
from datetime import datetime


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True,unique=True)
    email = db.Column(db.String(128), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship('Post', backref='author', lazy='dynamic')

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128), index=True)
    body = db.Column(db.Text)
    html_body = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    type = db.Column(db.Enum('post', 'review'), default='post')
    age = db.Column(db.Integer)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Post {}>'.format(self.body)

    @staticmethod
    def on_body_change(target, value, oldvalue, initiator):
        allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                        'h1', 'h2', 'h3', 'h4', 'h5', 'p', 'hr', 'img',
			'video', 'div', 'iframe', 'br', 'span', 'src', 'class']

        allowed_attrs = {'*': ['class'],
                         'a': ['href', 'rel'],
                         'img': ['src', 'alt']}

        html_body = markdown(value, output_format='html', extensions=['markdown.extensions.extra', 'markdown.extensions.codehilite', 'markdown.extensions.tables', 'markdown.extensions.toc'])
        html_body = bleach.clean(html_body, tags=allowed_tags, strip=True, attributes=allowed_attrs)
        html_body = bleach.linkify(html_body)
        target.html_body = html_body


db.event.listen(Post.body, 'set', Post.on_body_change)


@login.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_admin import Admin
from flask_sqlalchemy import SQLAlchemy
from flask_moment import Moment
from flask_login import LoginManager
from config import Config

bootstrap = Bootstrap()
admin = Admin(name='Blog', template_mode='bootstrap3')
db = SQLAlchemy()
moment = Moment()
login = LoginManager()

# from app.models import User, Post


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    # Config.init_app(app)

    bootstrap.init_app(app)
    admin.init_app(app)
    db.init_app(app)
    moment.init_app(app)
    login.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    return app


app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import views

app/main/views.py
from app.main import bp
from flask import render_template
from app import admin
from app.models import User, Post, db
from flask_admin import form
from flask_admin.contrib.sqla import ModelView
from flask_login import current_user


@bp.route('/')
def hello_world():
    posts = Post.query.filter_by(type='post')
    return render_template('index.html', title='Essay', posts=posts)

@bp.route('/review')
def show_reviews():
    posts = Post.query.filter_by(type='review')
    return render_template('index.html', title='Review', posts=posts)


@bp.route('/p/<int:id>')
def get_blog(id):
    post = Post.query.get(id)
    return render_template('post.html', post=post)


# flask-admin 自定义定制view

# list 过滤
# class MicroBlogModelView(ModelView):
#    column_exclude_list = ['password_hash', 'html_body']
# admin.add_view(MicroBlogModelView(User, db.session))
# admin.add_view(MicroBlogModelView(Post, db.session))


# create form 过滤，filter
class MyBaseForm(form.BaseForm):
    def do_something(self):
        pass


class MyModelView(ModelView):
    form_base_class = MyBaseForm
    form_excluded_columns = ('password_hash', 'html_body')
    column_exclude_list = ['password_hash', 'html_body']

# 控制访问后台页面的权限，经过认证的才能访问
    def is_accessible(self):
        return current_user.is_authenticated


admin.add_view(MyModelView(User, db.session))
admin.add_view(MyModelView(Post, db.session))

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block head %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>AlexLang-Blog</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../static/blog.css" rel="stylesheet">

    <!-- Custom styles for this markdown -->
    <link href="../static/md.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script>
	var _hmt = _hmt || [];
	(function() {
	  var hm = document.createElement("script");
	  hm.src = "https://hm.baidu.com/hm.js?270fb2f00fc83b77f9f6fd488b767361";
	  var s = document.getElementsByTagName("script")[0]; 
	  s.parentNode.insertBefore(hm, s);
	})();
    </script>

{% endblock %}

{% block navbar %}
  <div class="navbar navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span>
          <span class="icon-bar"></span><span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/" rel="external nofollow" >Blog</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="/" rel="external nofollow" >Essay</a></li>
          <li><a href="{{ url_for('main.show_reviews') }}" rel="external nofollow">Review</a></li>
          <li><a href="{{ url_for('auth.login') }}" rel="external nofollow" target="_blank">Admin</a></li>
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-info", role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% block app_content %}{% endblock %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}


{% block app_content %}
    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">郎晓伟 {{ title }}</h1>
        <p class="lead blog-description" align="center"><b>人生苦短，我用Python</b></p>
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">
            {% for post in posts %}
                <div class="blog-post">
                <h2 class="blog-post-title"><a href="{{ url_for('main.get_blog',id=post.id) }}">{{ post.title }}</a> </h2>
                <p class="blog-post-meta">{{ moment(post.timestamp).format('YYYY-M-D') }} by {{ post.author.username }}</p>
                {#{{ post.html_body| safe | truncate(200, True)}} #}
                </div><!-- /.alex_blog-post -->
            {% endfor %}
        </div><!-- /.alex_blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>关于</h4>
            <p>吃的苦中苦，背得锅上锅。</p>
          </div>
          <div class="sidebar-module">
            <h4>归档</h4>
            <ol class="list-unstyled">
              <li><a href="#">十二月</a></li>
              <li><a href="#">十一月</a></li>
              <li><a href="#">十月</a></li>
              <li><a href="#">九月</a></li>
              <li><a href="#">八月</a></li>
              <li><a href="#">七月</a></li>
              <li><a href="#">六月</a></li>
              <li><a href="#">五月</a></li>
              <li><a href="#">四月</a></li>
              <li><a href="#">三月</a></li>
              <li><a href="#">二月</a></li>
              <li><a href="#">一月</a></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>链接</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.alex_blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

{% endblock %}

app/templates/post.html
{% extends "base.html" %}

{% block app_content %}
    <div class="container">

      <div class="row">

        <div class="col-md-10 blog-main">
                {{ post.html_body | safe }}
        </div><!-- /.alex_blog-main -->
          <div class="col-md-2"></div>
{#
        <div class="col-md-1 col-sm-offset-1 alex_blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
              <li><a href="#">September 2013</a></li>
              <li><a href="#">August 2013</a></li>
              <li><a href="#">July 2013</a></li>
              <li><a href="#">June 2013</a></li>
              <li><a href="#">May 2013</a></li>
              <li><a href="#">April 2013</a></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.alex_blog-sidebar -->
#}
      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

{% endblock %}